version: "3"

services:
  api:
    build: .
    image: api
    ports:
      - "4000:4000"
    volumes:
      - ".:/go/src/app"

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data:
